---
- name: Prepare nodes
  hosts: kube
  remote_user: root

  tasks:
    - name: Install nfs-common
      ansible.builtin.apt:
        name: nfs-common
        state: present
    - name: Install open-iscsi
      ansible.builtin.apt:
        name: open-iscsi
        state: present
    - name: Install util-linux
      ansible.builtin.apt:
        name: util-linux
        state: present
    - name: Create storage path
      ansible.builtin.file:
        path: /storage
        state: directory
        mode: '0755'
    